### ISSUE TITLE
Problem on upload image

### ISSUE THREAD

**Issue by teal33t** [CitizensFoundation/your-priorities-app#28]
Hi
I got a problem with image uploading, Imagemagick is also installed. 

```
[2018-11-08T15:11:02.687Z] ERROR: your-priorities/6719 on mardom.foundation:
    Image Error { context: 's3UploadClient',
      image: null,
      user: null,
      err:
       { Error: Command failed: identify -format "name=
    size=%[size]
    format=%m
    colorspace=%[colorspace]
    height=%[height]
    width=%[width]
    orientation=%[orientation]
    " uploads/0962cc7a51048c62259ac7041b588ff1
    identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.

        at ChildProcess.exithandler (child_process.js:275:12)
        at emitTwo (events.js:126:13)
        at ChildProcess.emit (events.js:214:7)
        at maybeClose (internal/child_process.js:925:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
         killed: false,
         code: 1,
         signal: null,
         cmd: 'identify -format "name=\nsize=%[size]\nformat=%m\ncolorspace=%[colorspace]\nheight=%[height]\nwidth=%[width]\norientation=%[orientation]\n" uploads/0962cc7a51048c62259ac7041b588ff1' },
      errorStatus: 500 }
::ffff:89.196.158.105 - - [08/Nov/2018:15:11:02 +0000] "POST /api/images?itemType=user-header HTTP/1.1" 500 21 "http://x.x.x.x:4242/domain/1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:63.0) Gecko/20100101 Firefox/63.0"
```
any Idea?

**Comment by rbjarnason** [comment]
@thelematic I'm not sure, its an error from the identify command - found this on StakOverflow: https://stackoverflow.com/questions/9586048/imagemagick-no-decode-delegate and https://stackoverflow.com/questions/9144402/rspec-paperclip-identify-no-decode-delegate-for-this-image-format

**Comment by teal33t** [comment]
@rbjarnason  I found that this problem is cuz of Imagemagick dependency for libjpeg. 
so I installed libjpeg-dev and it works now

**Comment by rbjarnason** [comment]
@thelematic Great :)
